<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Proxy.Config</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
